// Code generated by MockGen. DO NOT EDIT.
// Source: notification.go
//
// Generated by this command:
//
//	mockgen -source=notification.go -destination=mocks/notification_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/liliksetyawan/realtimehub/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationRepository is a mock of NotificationRepository interface.
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationRepositoryMockRecorder is the mock recorder for MockNotificationRepository.
type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

// NewMockNotificationRepository creates a new mock instance.
func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

// AckedSeq mocks base method.
func (m *MockNotificationRepository) AckedSeq(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AckedSeq", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AckedSeq indicates an expected call of AckedSeq.
func (mr *MockNotificationRepositoryMockRecorder) AckedSeq(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AckedSeq", reflect.TypeOf((*MockNotificationRepository)(nil).AckedSeq), ctx, userID)
}

// Create mocks base method.
func (m *MockNotificationRepository) Create(ctx context.Context, n *domain.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotificationRepositoryMockRecorder) Create(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationRepository)(nil).Create), ctx, n)
}

// CurrentSeq mocks base method.
func (m *MockNotificationRepository) CurrentSeq(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentSeq", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentSeq indicates an expected call of CurrentSeq.
func (mr *MockNotificationRepositoryMockRecorder) CurrentSeq(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentSeq", reflect.TypeOf((*MockNotificationRepository)(nil).CurrentSeq), ctx, userID)
}

// ListByUser mocks base method.
func (m *MockNotificationRepository) ListByUser(ctx context.Context, userID string, unreadOnly bool, limit, offset int) ([]*domain.Notification, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, unreadOnly, limit, offset)
	ret0, _ := ret[0].([]*domain.Notification)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockNotificationRepositoryMockRecorder) ListByUser(ctx, userID, unreadOnly, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockNotificationRepository)(nil).ListByUser), ctx, userID, unreadOnly, limit, offset)
}

// MarkRead mocks base method.
func (m *MockNotificationRepository) MarkRead(ctx context.Context, userID, notificationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRead", ctx, userID, notificationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRead indicates an expected call of MarkRead.
func (mr *MockNotificationRepositoryMockRecorder) MarkRead(ctx, userID, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRead", reflect.TypeOf((*MockNotificationRepository)(nil).MarkRead), ctx, userID, notificationID)
}

// RecordAck mocks base method.
func (m *MockNotificationRepository) RecordAck(ctx context.Context, userID string, upToSeq int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordAck", ctx, userID, upToSeq)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordAck indicates an expected call of RecordAck.
func (mr *MockNotificationRepositoryMockRecorder) RecordAck(ctx, userID, upToSeq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordAck", reflect.TypeOf((*MockNotificationRepository)(nil).RecordAck), ctx, userID, upToSeq)
}

// SinceSeq mocks base method.
func (m *MockNotificationRepository) SinceSeq(ctx context.Context, userID string, fromSeq int64, limit int) ([]*domain.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SinceSeq", ctx, userID, fromSeq, limit)
	ret0, _ := ret[0].([]*domain.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SinceSeq indicates an expected call of SinceSeq.
func (mr *MockNotificationRepositoryMockRecorder) SinceSeq(ctx, userID, fromSeq, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SinceSeq", reflect.TypeOf((*MockNotificationRepository)(nil).SinceSeq), ctx, userID, fromSeq, limit)
}

// UnreadCount mocks base method.
func (m *MockNotificationRepository) UnreadCount(ctx context.Context, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnreadCount", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnreadCount indicates an expected call of UnreadCount.
func (mr *MockNotificationRepositoryMockRecorder) UnreadCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnreadCount", reflect.TypeOf((*MockNotificationRepository)(nil).UnreadCount), ctx, userID)
}

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// SendNotification mocks base method.
func (m *MockPublisher) SendNotification(ctx context.Context, userID string, n *domain.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNotification", ctx, userID, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNotification indicates an expected call of SendNotification.
func (mr *MockPublisherMockRecorder) SendNotification(ctx, userID, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNotification", reflect.TypeOf((*MockPublisher)(nil).SendNotification), ctx, userID, n)
}
